### ISSUE TITLE
iframes load after screenshot is taken

### ISSUE THREAD

**Issue by jongrover** [learn-co-curriculum/html-map-contact-form-code-along#3] opened 2016-03-28 21:41 UTC
iframes load too slowly for screenshot test with green onion. Need to figure out how to delay screenshot till after iframe loads or calibrate the tolerance to not effect the outcome.

**Comment by pletcher** [comment] 2016-06-03 14:01
This repo doesn't use GreenOnion -- the issue is on the GreenOnion-using repo, though, so we'll close this here.

**Closed by pletcher** 2016-06-03 14:01 UTC
